# Generated by Django 2.1.4 on 2018-12-29 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_type', models.CharField(default='', help_text='地域类别', max_length=20, verbose_name='地域类别')),
                ('city_name', models.CharField(default='', help_text='城市名', max_length=20, verbose_name='城市名')),
                ('city_en_name', models.CharField(default='', help_text='城市名拼音', max_length=200, verbose_name='城市名拼音')),
                ('latitude', models.FloatField(blank=True, help_text='纬度', null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, help_text='经度', null=True, verbose_name='经度')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市列表',
                'verbose_name_plural': '城市列表',
            },
        ),
        migrations.CreateModel(
            name='CitesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_type', models.CharField(default='', help_text='地域类别', max_length=20, verbose_name='地域类别')),
                ('type_name', models.CharField(default='', help_text='城市类别', max_length=20, verbose_name='城市类别')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市类别',
                'verbose_name_plural': '城市类别',
            },
        ),
        migrations.CreateModel(
            name='HotCites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_type', models.CharField(default='', help_text='地域类别', max_length=20, verbose_name='地域类别')),
                ('city_name', models.CharField(default='', help_text='城市名', max_length=20, verbose_name='城市名')),
                ('city_en_name', models.CharField(default='', help_text='城市名拼音', max_length=200, verbose_name='城市名拼音')),
                ('latitude', models.FloatField(blank=True, help_text='纬度', null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, help_text='经度', null=True, verbose_name='经度')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热门城市列表',
                'verbose_name_plural': '热门城市列表',
            },
        ),
    ]
